export default
{
    "villes": [
        "casablanca",
        "fes",
        "tanger",
        "marrakech",
        "salé",
        "meknes",
        "rabat",
        "oujda",
        "kenitra",
        "agadir",
        "tétouan",
        "temara",
        "safi",
        "mohammedia",
        "khouribga",
        "el jadida",
        "beni mellal",
        "ait melloul",
        "nador",
        "dar bouazza",
        "taza",
        "settat",
        "berrechid",
        "khemisset",
        "inezgane",
        "ksar el kebir",
        "larache",
        "guelmim",
        "khenifra",
        "berkane",
        "taourirt",
        "bouskoura",
        "Fquih Ben Salah",
        "Dcheira El Jihadia",
        "Oued Zem",
        "El Kelaa Des Sraghna",
        "Sidi Slimane",
        "Errachidia",
        "Guercif",
        "Oulad Teima",
        "Ben Guerir",
        "Tifelt",
        "Lqliaa",
        "Taroudant",
        "Sefrou",
        "Essaouira",
        "Fnideq",
        "Sidi Kacem",
        "Tiznit",
        "Tan-Tan",
        "Ouarzazate",
        "Souk El Arbaa",
        "Youssoufia",
        "Lahraouyine",
        "Martil",
        "Ain Harrouda",
        "Suq as-Sabt Awlad an-Nama",
        "Skhirat",
        "Ouazzane",
        "Benslimane",
        "Al Hoceima",
        "Beni Ansar",
        "M'diq",
        "Sidi Bennour",
        "Midelt",
        "Azrou",
        "Drargua"
    ]
}